[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'puremourning/vimspector'
hook_add = '''
    let g:vimspector_enable_mappings = 'VISUAL_STUDIO'
    let g:vimspector_install_gadgets = ['vscode-node-debug2']
'''
on_ft = ['javascript', 'typescript']
